name: Build Linux Kernel

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: arc-runner-set-kernel
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libncurses-dev \
            bison \
            flex \
            libssl-dev \
            libelf-dev \
            wget \
            xz-utils \
            bc \
            dwarves \
            cpio \
            liblz4-tool \
            python3 \
            git \
            debhelper \
            dh-python \
            kmod \
            rsync \
            fakeroot \
            libudev-dev \
            libpci-dev \
            liblzma-dev \
            libzstd-dev

      - name: Cache Linux kernel tarball
        uses: actions/cache@v4
        with:
          path: linux-6.12.32.tar.xz
          key: linux-kernel-6.12.32

      - name: Download Linux kernel source
        run: |
          if [ ! -f linux-6.12.32.tar.xz ]; then
            wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.12.32.tar.xz
          fi
          tar -xf linux-6.12.32.tar.xz

      - name: Prepare kernel config
        run: |
          cp $GITHUB_WORKSPACE/x86_64_config linux-6.12.32/.config

      - name: Set kernel localversion
        run: |
          cd linux-6.12.32
          make olddefconfig
          DATE=$(date +%y%m%d%H%M)
          sed -i "/^CONFIG_LOCALVERSION=/d" .config
          echo "CONFIG_LOCALVERSION=\"-styx-$DATE\"" >> .config
          scripts/config --set-str LOCALVERSION "-styx-$DATE"
          scripts/config --disable LOCALVERSION_AUTO

      - name: Update debian changelog for custom version
        run: |
          cd linux-6.12.32
          DATE=$(date +%y%m%d%H%M)
          sed -i "1s/(\(.*\))/\(6.12.32-styx-$DATE-1\)/" debian/changelog

      - name: Initialize git repo in kernel source
        run: |
          cd linux-6.12.32
          git init
          git config user.email "ci@example.com"
          git config user.name "CI"
          git add .
          git commit -m "init"

      - name: Build kernel and generate .deb packages
        run: |
          cd linux-6.12.32
          fakeroot make -j$(nproc) deb-pkg

      - name: Add postinst script for kernel package
        run: |
          cd linux-6.12.32
          for pkg in debian/*; do
            if echo "$pkg" | grep -q '^debian/linux-image'; then
cat <<'EOF' > debian/postinst
#!/bin/sh
set -e
if [ "$1" = "configure" ]; then
  update-initramfs -c -k "$2" || true
  if command -v update-grub >/dev/null 2>&1; then
    update-grub || true
  elif command -v grub-mkconfig >/dev/null 2>&1; then
    grub-mkconfig -o /boot/grub/grub.cfg || true
  fi
fi
exit 0
EOF
              chmod +x debian/postinst
            fi
          done

      - name: Upload .deb packages to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: "*.deb"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
